module.exports = {
  DEFAULT_EXCLUDE: [
    "password",
    "createdAt",
    "updatedAt",
    "deletedAt",
    "id",
    "userId",
    "otp",
    "businessId",
    "roleId",
    "resetToken",
    "resetTokenExpiry",
    "businessUserRoles",
    "accessToken",
    "zoneId",
    "floorId",
    "parentCategoryId",
    "itemId",
    "categoryId",
  ],
};
